# Configuración de conexión (Se autocompleta con las variables de Docker, pero aseguramos los mapeos)
MYSQLCrypt     crypt
MYSQLTarget    custom

# Consultas personalizadas para la estructura de Laravel
MYSQLGetPW     SELECT password FROM ftp_users WHERE user="\L"
MYSQLGetUID    SELECT uid FROM ftp_users WHERE user="\L"
MYSQLGetGID    SELECT gid FROM ftp_users WHERE user="\L"
MYSQLGetDir    SELECT dir FROM ftp_users WHERE user="\L"
