version: '3.6'

services:
  ftp:
    container_name: ddev-${DDEV_SITENAME}-ftp
    image: stilliard/pure-ftpd
    ports:
      - "0.0.0.0:21:21"
      - "0.0.0.0:30000-30009:30000-30009"
    volumes:
      # Almacenamiento de archivos de empleados de Utrecar
      - ./data:/home/ftpusers
      # Inyectamos vuestro mapeo de consultas personalizado para Pure-FTPd
      - ./db/mysql.conf:/etc/pure-ftpd/db/mysql.conf
    environment:
      PUBLICHOST: "ftp.utrecar.com"
      MIN_PASV_PORT: 30000
      MAX_PASV_PORT: 30009

      # 👇 USAMOS LA VARIABLE NATIVA DE LA IMAGEN (ADIÓS ADDED_FLAGS)
      PURE_FTPD_FLAGS: "-d -c 50 -C 10 -R -l mysql:/etc/pure-ftpd/db/mysql.conf"

      # Conexión directa a la base de datos MariaDB
      MYSQL_FILE: "/etc/pure-ftpd/db/mysql.conf"
      DB_HOST: "db"
      DB_USER: "db"
      DB_PASS: "db"
      DB_NAME: "db"
    restart: always

    labels:
      com.ddev.site-name: ${DDEV_SITENAME}